import JSZip from 'jszip';
import { saveAs } from 'file-saver';
import type { Project } from '../types';
import { ExpressGenerator } from '../generators/express/ExpressGenerator';
import { SwaggerGenerator } from '../generators/swagger/SwaggerGenerator';

export class ProjectExporter {
    private project: Project;

    constructor(project: Project) {
        this.project = project;
    }

    async exportAsZip(): Promise<void> {
        const zip = new JSZip();

        // Generate Express backend
        const expressGenerator = new ExpressGenerator(this.project);
        const expressFiles = expressGenerator.generate();

        // Generate Swagger spec
        const swaggerGenerator = new SwaggerGenerator(this.project);
        const { swaggerJsFile } = swaggerGenerator.generate();

        // Add Express files to zip
        expressFiles.forEach(file => {
            zip.file(file.path, file.content);
        });

        // Add Swagger file
        zip.file('src/swagger.js', swaggerJsFile);

        // Add README
        zip.file('README.md', this.generateReadme());

        // Add auth middleware (if needed)
        if (this.hasAuthNodes()) {
            zip.file('src/middleware/auth.js', this.generateAuthMiddleware());
        }

        // Add .gitignore
        zip.file('.gitignore', this.generateGitignore());

        // Generate zip
        const blob = await zip.generateAsync({ type: 'blob' });
        const projectName = this.project.name.toLowerCase().replace(/\s+/g, '-');
        saveAs(blob, `${projectName}-backend.zip`);
    }

    private hasAuthNodes(): boolean {
        return this.project.nodes.some(n => n.data.type === 'auth');
    }

    private generateAuthMiddleware(): string {
        return `const jwt = require('jsonwebtoken');

const authMiddleware = (req, res, next) => {
  try {
    const authHeader = req.headers.authorization;
    
    if (!authHeader || !authHeader.startsWith('Bearer ')) {
      return res.status(401).json({ error: 'No token provided' });
    }

    const token = authHeader.split(' ')[1];
    const decoded = jwt.verify(token, process.env.JWT_SECRET);
    
    req.user = decoded;
    next();
  } catch (error) {
    return res.status(401).json({ error: 'Invalid token' });
  }
};

module.exports = { authMiddleware };
`;
    }

    private generateReadme(): string {
        const projectName = this.project.name;
        const basePath = this.project.settings.basePath;
        const port = this.project.settings.port;

        return `# ${projectName}

> Generated by [Routify](https://github.com/your-repo/routify) - No-Code Backend Builder

## 🚀 Quick Start

### Prerequisites
- Node.js 18+
- MongoDB

### Installation

\`\`\`bash
# Install dependencies
npm install

# Copy environment file
cp .env.example .env

# Edit .env with your MongoDB connection string
nano .env

# Start development server
npm run dev
\`\`\`

### Environment Variables

| Variable | Description | Default |
|----------|-------------|---------|
| PORT | Server port | ${port} |
| MONGODB_URI | MongoDB connection string | - |
| JWT_SECRET | Secret for JWT tokens | - |

## 📚 API Documentation

Swagger UI is available at: \`http://localhost:${port}/docs\`

## 🐳 Docker

\`\`\`bash
# Build and run with Docker Compose
docker-compose up -d

# Or build manually
docker build -t ${projectName.toLowerCase().replace(/\s+/g, '-')} .
docker run -p ${port}:${port} ${projectName.toLowerCase().replace(/\s+/g, '-')}
\`\`\`

## ☁️ Deploy to Render

1. Push to GitHub
2. Connect repository in Render dashboard
3. Set environment variables
4. Deploy!

## 📝 API Endpoints

Base URL: \`${basePath}\`

| Method | Path | Description |
|--------|------|-------------|
${this.generateEndpointsTable()}

---

Made with ❤️ by Routify
`;
    }

    private generateEndpointsTable(): string {
        return this.project.nodes
            .filter(n => n.data.type === 'endpoint')
            .map(n => {
                const config = n.data.config as { method: string; path: string; description: string };
                return `| ${config.method} | ${config.path} | ${config.description || '-'} |`;
            })
            .join('\n');
    }

    private generateGitignore(): string {
        return `# Dependencies
node_modules/

# Environment
.env

# Build
dist/
build/

# Logs
logs/
*.log
npm-debug.log*

# OS
.DS_Store
Thumbs.db

# IDE
.idea/
.vscode/
*.swp
`;
    }
}
